name: Build & Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/release'
    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v2
      with:
        ref: 'release'
    - name: Get Submodule
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval `ssh-agent -s`
        echo "${{secrets.I18N_SUBMODULE_SSHKEY}}" | ssh-add -
        git config user.name github-actions
        git config user.email github-actions@github.com
        git submodule update --init --recursive
        ssh-add -D
        eval `ssh-agent -k`
    - name: Build
      run: |
        cd etc/build
        ant
    - name: Tag and Push
      run: |
        export VERSION=`cat VERSION`
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -a -m "Ready for $VERSION"
        git push
        git tag "diagramly-${VERSION//\./_}"
        git push origin "diagramly-${VERSION//\./_}"
