name: Build & Release

on:
  push:
    paths:
      - VERSION

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/release'
    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v2
      with:
        ref: 'release'
        submodules: 'recursive'
    - name: Build
      run: |
        cd etc/build
        ant
    - name: Tag and Push
      run: |
        export VERSION=`cat VERSION`
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -a -m "Ready for $VERSION"
        git tag "diagramly-${VERSION//\./_}"
        git push
